python -u utils/extract_results.py $dir \
                                   $dataset \
                                   $label_method \
                                   $query_method \
                                   $distribution \
                                   $label_range \
                                   $query_label_cnt \
                                   $ef_construction \
                                   $M \
                                   $serf_M \
                                   $K \
                                   $nprobe \
                                   $ef_search \
                                   $threads \
                                   $gamma \
                                   $M_beta \
                                   $alpha \
                                   $L \
                                   $partition_size_M \
                                   $beamsize \
                                   $split_factor \
                                   $shift_factor \
                                   $final_beam_multiply \
                                   $kgraph_L \
                                   $iter \
                                   $S \
                                   $R \
                                   $B \
                                   $kgraph_M \
                                   $weight_search \
                                   $dim \
                                   $N \
                                   $query_size \
                                   $acorn_index_file \
                                   $diskann_index_label_root \
                                   $rfann_index_prefix \
                                   $irange_index_file \
                                   $rii_index_file \
                                   $serf_index_file \
                                   $nhq_index_model_file \
                                   $nhq_index_attr_file \
                                   $ivfpq_index_file \
                                   $hnsw_index_file \
                                   $vtree_index_prefix \
                                   $nhqkg_index_model_file \
                                   $nhqkg_index_attr_file \
                                   $algo \
                                   $result_file